# Generated by Django 3.2.5 on 2021-07-29 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=64)),
                ('legal_name', models.CharField(max_length=64)),
                ('alt_name1', models.CharField(max_length=64)),
                ('alt_name2', models.CharField(max_length=64)),
                ('alt_name3', models.CharField(max_length=64)),
                ('Ticker', models.CharField(max_length=10)),
                ('org_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_sector', to='sector_app.sector')),
            ],
        ),
    ]
