# Generated by Django 3.2.5 on 2021-08-05 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sector_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_name', models.CharField(max_length=64)),
                ('maturity_date', models.DateField()),
                ('debt_amount', models.IntegerField()),
                ('debt_class', models.CharField(max_length=10)),
                ('debt_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_org', to='sector_app.organization')),
            ],
        ),
    ]
