# Generated by Django 3.2.5 on 2021-08-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sector_app', '0003_auto_20210807_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
